# Generated by Django 5.2.11 on 2026-06-06 17:44

import django.db.models.deletion
import pyotp
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_secret', models.CharField(default=pyotp.random_base32, editable=False, help_text="Clé secrète TOTP de l'utilisateur (générée automatiquement).", max_length=32, verbose_name='Secret OTP')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nom')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse e-mail')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='Mot de passe')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('groups', models.ManyToManyField(blank=True, to='auth.group', verbose_name='Groupes')),
                ('user_permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ('-date_joined',),
                'unique_together': {('phone_number', 'email')},
            },
        ),
        migrations.CreateModel(
            name='OtpToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='Token haché')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_token', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'jeton OTP',
                'verbose_name_plural': 'jetons OTP',
            },
        ),
    ]
