# Generated by Django 5.2.11 on 2026-04-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scb_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('phone_number', 'email')},
        ),
    ]
